# Setup
title:        One student "in the open"
tagline:      A semi-professional, less personal blog by a student exploring the open-source world
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Polina Koleva
  url:        https://github.com/polinankoleva

# Gems
gems:
  - jekyll-paginate
  - jemoji

#Others
markdown: kramdown
